
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: online_exam_service
  datasource:
    url: jdbc:mysql://localhost:3306/onlineexam?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '0213'
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates
    #spring.freemarker.template-loader-path=classpath:/templates/
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl